### ISSUE TITLE
Option to stop firing if too many sails in orbit

### ISSUE THREAD

**Issue by alpe12** [DanielHeEGG/SmartEjectors#2]
If possible, add an option to also only fire the ejectors if there's less than X (eg: 500) number of sails in orbit.
This way they won't fire beyond the capacity of the dyson sphere nodes to absorb them.
Thanks.

![image](https://user-images.githubusercontent.com/8551127/152582497-e74ae608-92a2-4772-8382-2cb0a808b7b3.png)

**Comment by DanielHeEGG** [comment]
If I understand correctly, you want an option to limit the sails in orbit due to the slow speed of absorption, and some sails might expire before getting absorbed?
Because the current logic already takes into account the number of sails in the swarm: the ejectors stop shooting when the amount of sails already absorbed + the amount of sails in orbit is greater than the total sail points of the sphere.
```
public static bool isSphereFilled(DysonSphere sphere)
{
    return sphere.totalConstructedCellPoint + sphere.swarm.sailCount >= sphere.totalCellPoint;
}
```

**Comment by alpe12** [comment]
I see. Thanks.

Does `sphere.swarm.sailCount` count both sails being absorbed and the ones in orbit not being absorbed yet?

**Comment by DanielHeEGG** [comment]
Yes, counts for the blue ones and the yellow ones.

**Comment by alpe12** [comment]
I started a new Dyson Sphere layer.
I had a problem with my "Small carrier rocket" deliveries.
But the Solar sails keeped being fired. And soon I had 10000 sails in orbit with only a few noded to absorb them.
So this function could still be useful in these cases.

**Comment by DanielHeEGG** [comment]
I'm planning on implementing that, but a more dynamic version - max sails in orbit proportional to the amount of nodes available to absorb them. Will have to take a look at the source code again, might take a while.

**Comment by alpe12** [comment]
> proportional to the amount of nodes

That would indeed be better than an absolute number.

> might take a while.

No problem. But in the meantime, can't you add an absolute number instead? Even a big number like 5000 would already help a lot.

Is there already a parameter that holds only the number of sails in orbit (yellow)? So I can implement it locally with something like:
`return sphere.totalConstructedCellPoint + sphere.swarm.sailCount >= sphere.totalCellPoint ^ X > 500;` while the mod insn't updated.

Thanks anyway. :)
