### ISSUE TITLE
Dyson Sphere/Swarm Orbit is filled when there are no sails in the orbits?

### ISSUE THREAD

**Issue by Timtee** [DanielHeEGG/SmartEjectors#3]
As the title says, The rail ejectors say that the orbits are full when there is nothing in them. I have no idea why this is happening exactly, but I know for a fact that the rail ejectors can't fire because well... without this mod, they'd most likely fire. (And personally, I don't want to have to remove the mod because of this problem anyways...) 

I also have provided imgs to show what I mean.
![image](https://user-images.githubusercontent.com/38089299/152700377-ea0db56d-80f1-4411-a86c-15d8678d40c5.png)
![image](https://user-images.githubusercontent.com/38089299/152700507-e6d554c4-ef61-4e70-8fec-7990f306572f.png)

I honestly have no clue what within this mod would exactly cause it beyond something within the code for detecting if a orbit or sphere is full or not. But I don't think it accounts for not having access to the sphere itself yet.

**Comment by DanielHeEGG** [comment]
Could you provide a screenshot of your Dyson Sphere planning window?

**Comment by Timtee** [comment]
> Could you provide a screenshot of your Dyson Sphere planning window?

![image](https://user-images.githubusercontent.com/38089299/152701230-b77163f2-540f-45f9-84e2-b79133e89ab9.png)
Gotcha. All the orbits are just what the game generated. I don't have the dyson spheres researched yet on this save tho.

**Comment by DanielHeEGG** [comment]
Yeah, the whole point of this mod is that it stops the ejectors from firing into the swarm. If you do the math, swarms are pretty inefficient compared to hydrogen fuel rods. If you want a swarm but still want other features of this mod (ie. auto select orbit 1), you can disable it by setting `enableLockEjector` to `false` in the config file.
