### ISSUE TITLE
Possible Mod Interference w/ RailGunsRetargeting

### ISSUE THREAD

**Issue by korishan** [DanielHeEGG/SmartEjectors#4]
I had both SmartEjectors and RailGunsRetargeting installed. And when I got to progression to launch sails, the guns weren't firing. I changed assigned orbits, but nothing. I changed locations on the planet, nothing. The RG's would follow the assigned path, but just wouldn't fire.
As soon as I disabled SmartEjectors, they started firing off.
Could there be an interference issue between these two mods? RGR mod will cycle through the orbits for the best/inrange orbit, and SE is trying to use Orbit 1 by default. Could this be the issue?

These are the only two mods for the Rail Guns I've used/installed.

Kori

**Comment by DanielHeEGG** [comment]
Do you have a dyson sphere frame built yet? This mod is designed to prevent a dyson swarm from forming due to its inefficiency. See issue #3.

**Comment by korishan** [comment]
Ok, thanks Daniel.  I thought the purpose of the mod was that once a shell was full, the Ejectors/Railguns would stop firing until sails depleted enough to cause them to start firing again.  I suppose I just misunderstood the purpose. 
Thanks.
